/**
 * Dados mockados para demonstração offline.
 * Todos os IDs são strings simples para facilitar referencias cruzadas.
 */

export const MOCK_USER = {
  id: "user-admin-1",
  email: "admin@senaisp.edu.br",
  full_name: "Carlos Alberto Mendes",
  role: "admin",
};

export const MOCK_PROJECTS = [
  {
    id: "proj-1",
    title: "Sistema de Gestão Energética com IoT",
    description: "Desenvolvimento de um sistema integrado de monitoramento e controle de consumo energético industrial utilizando dispositivos IoT, dashboards em tempo real e algoritmos de otimização baseados em IA.",
    abstract: "Solução para reduzir desperdício energético em ambientes industriais com sensores IoT e inteligência artificial, projetando economia de até 35% no consumo.",
    category: "energia",
    team_name: "Grupo Alpha-4",
    advisor: "Prof. Dr. Ricardo Alves",
    room: "Auditório A",
    schedule_time: "09:00 - 09:30",
    presentation_type: "oral",
    oral_approved: true,
    banner_url: "https://images.unsplash.com/photo-1509391366360-2e959784a276?w=800&q=80",
    thumbnail_url: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=400&q=80",
    slides_url: "https://example.com/slides1.pdf",
    article_url: "https://example.com/artigo1.pdf",
    pitch_youtube_url: "https://youtube.com/watch?v=dQw4w9WgXcQ",
    github_url: "https://github.com/grupo-alpha4/iot-energy",
    status: "aprovado",
    keywords: ["IoT", "energia", "indústria 4.0", "IA", "sustentabilidade"],
    members: [
      { name: "Lucas Ferreira", email: "lucas@senaisp.edu.br" },
      { name: "Ana Paula Costa", email: "ana@senaisp.edu.br" },
      { name: "Bruno Souza", email: "bruno@senaisp.edu.br" },
    ],
    created_date: "2026-03-10T09:00:00Z",
    updated_date: "2026-04-20T14:00:00Z",
    created_by: "lucas@senaisp.edu.br",
  },
  {
    id: "proj-2",
    title: "Braço Robótico Colaborativo para Linha de Montagem",
    description: "Protótipo de braço robótico 6-DOF com capacidade colaborativa (cobot), sensores de força-torque e visão computacional para inspeção de qualidade em linhas de produção.",
    abstract: "Cobot de baixo custo capaz de trabalhar ao lado de operadores humanos, aumentando produtividade em 40% sem comprometer a segurança.",
    category: "mecatronica",
    team_name: "RoboTeam SP",
    advisor: "Prof. Me. Fernanda Lima",
    room: "Lab de Mecatrônica",
    schedule_time: "10:00 - 10:30",
    presentation_type: "oral",
    oral_approved: true,
    banner_url: "https://images.unsplash.com/photo-1561557944-6e7860d1a7eb?w=800&q=80",
    thumbnail_url: "https://images.unsplash.com/photo-1485827404703-89b55fcc595e?w=400&q=80",
    slides_url: "https://example.com/slides2.pdf",
    article_url: null,
    pitch_youtube_url: null,
    github_url: "https://github.com/roboteam-sp/cobot",
    status: "aprovado",
    keywords: ["robótica", "cobot", "visão computacional", "automação"],
    members: [
      { name: "Pedro Henrique Rocha", email: "pedro@senaisp.edu.br" },
      { name: "Mariana Oliveira", email: "mariana@senaisp.edu.br" },
    ],
    created_date: "2026-03-12T10:00:00Z",
    updated_date: "2026-04-22T11:00:00Z",
    created_by: "pedro@senaisp.edu.br",
  },
  {
    id: "proj-3",
    title: "Plataforma de Gestão de Estoques com Previsão por ML",
    description: "Sistema web para gerenciamento de estoques com módulo de previsão de demanda baseado em Machine Learning, integrado com ERP via API REST.",
    abstract: "Redução de ruptura de estoque em 60% e de excesso em 25% usando modelos preditivos de séries temporais (ARIMA + LSTM).",
    category: "software",
    team_name: "CodeFlow",
    advisor: "Prof. Dr. Marcelo Santos",
    room: null,
    schedule_time: null,
    presentation_type: "banner",
    oral_approved: false,
    banner_url: "https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=800&q=80",
    thumbnail_url: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=400&q=80",
    slides_url: null,
    article_url: "https://example.com/artigo3.pdf",
    pitch_youtube_url: "https://youtube.com/watch?v=dQw4w9WgXcQ",
    github_url: "https://github.com/codeflow/stock-ai",
    status: "aprovado",
    keywords: ["machine learning", "estoque", "ERP", "LSTM", "previsão"],
    members: [
      { name: "Juliana Martins", email: "juliana@senaisp.edu.br" },
      { name: "Rafael Torres", email: "rafael@senaisp.edu.br" },
      { name: "Camila Dias", email: "camila@senaisp.edu.br" },
    ],
    created_date: "2026-03-15T08:00:00Z",
    updated_date: "2026-04-25T16:00:00Z",
    created_by: "juliana@senaisp.edu.br",
  },
  {
    id: "proj-4",
    title: "Otimização de Rotas Logísticas com Algoritmos Genéticos",
    description: "Aplicação de algoritmos genéticos e ant colony optimization para resolver o problema de roteamento de veículos (VRP) em operações de entrega last-mile.",
    abstract: "Redução de 22% no custo total de frota e 18% no tempo de entrega em simulações com dados reais de uma transportadora parceira.",
    category: "logistica",
    team_name: "LogiOpt",
    advisor: "Prof. Dr. Sérgio Nakamura",
    room: null,
    schedule_time: null,
    presentation_type: "banner",
    oral_approved: false,
    banner_url: "https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=800&q=80",
    thumbnail_url: null,
    slides_url: null,
    article_url: null,
    pitch_youtube_url: null,
    github_url: "https://github.com/logiopt/vrp-genetic",
    status: "aprovado",
    keywords: ["logística", "algoritmos genéticos", "VRP", "otimização"],
    members: [
      { name: "Thiago Barbosa", email: "thiago@senaisp.edu.br" },
      { name: "Letícia Carvalho", email: "leticia@senaisp.edu.br" },
    ],
    created_date: "2026-03-20T11:00:00Z",
    updated_date: "2026-04-28T09:00:00Z",
    created_by: "thiago@senaisp.edu.br",
  },
  {
    id: "proj-5",
    title: "Automação de Processos Químicos com CLP Programável",
    description: "Sistema de controle e supervisão (SCADA) para automação de reações químicas em batelada, com alarmes, receituário digital e rastreabilidade GMP.",
    abstract: "Automação de 4 reatores de batelada com ganho de 30% em throughput e conformidade total com normas GMP/FDA para industria farmacêutica.",
    category: "quimica",
    team_name: "ChemAuto",
    advisor: "Profa. Dra. Beatriz Monteiro",
    room: "Lab de Química Industrial",
    schedule_time: "14:00 - 14:30",
    presentation_type: "oral",
    oral_approved: false,
    banner_url: "https://images.unsplash.com/photo-1532187863486-abf9dbad1b69?w=800&q=80",
    thumbnail_url: null,
    slides_url: null,
    article_url: null,
    pitch_youtube_url: null,
    github_url: null,
    status: "submetido",
    keywords: ["química", "SCADA", "CLP", "GMP", "automação"],
    members: [
      { name: "Gabriela Fonseca", email: "gabriela@senaisp.edu.br" },
      { name: "Diego Pimentel", email: "diego@senaisp.edu.br" },
      { name: "Natalia Ribeiro", email: "natalia@senaisp.edu.br" },
    ],
    created_date: "2026-03-25T13:00:00Z",
    updated_date: "2026-04-30T10:00:00Z",
    created_by: "gabriela@senaisp.edu.br",
  },
  {
    id: "proj-6",
    title: "Dashboard de KPIs para Gestão de Manutenção Preditiva",
    description: "Painel executivo integrado com sensores de vibração e temperatura para predição de falhas em equipamentos industriais usando modelos de anomalia.",
    abstract: "Redução de 45% em paradas não planejadas e economia estimada de R$ 2,3M/ano em uma planta piloto com 120 equipamentos monitorados.",
    category: "gestao",
    team_name: "MaintControl",
    advisor: "Prof. Me. Antonio Ferraz",
    room: null,
    schedule_time: null,
    presentation_type: "banner",
    oral_approved: false,
    banner_url: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&q=80",
    thumbnail_url: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=400&q=80",
    slides_url: null,
    article_url: "https://example.com/artigo6.pdf",
    pitch_youtube_url: null,
    github_url: "https://github.com/maintcontrol/dashboard",
    status: "aprovado",
    keywords: ["manutenção preditiva", "KPI", "dashboard", "Industry 4.0"],
    members: [
      { name: "Henrique Azevedo", email: "henrique@senaisp.edu.br" },
      { name: "Priscila Gomes", email: "priscila@senaisp.edu.br" },
    ],
    created_date: "2026-03-28T08:00:00Z",
    updated_date: "2026-04-29T15:00:00Z",
    created_by: "henrique@senaisp.edu.br",
  },
  {
    id: "proj-7",
    title: "Sistema de Automação Predial com Protocolo BACnet",
    description: "Implementação de sistema BMS (Building Management System) com protocolo BACnet IP para automação de iluminação, HVAC e segurança em edifício comercial.",
    abstract: "Integração de 350 pontos de controle em um edifício de 12 andares, com economia de 28% em energia e conformidade com LEED.",
    category: "automacao",
    team_name: "BuildAuto",
    advisor: "Prof. Dr. Ricardo Alves",
    room: null,
    schedule_time: null,
    presentation_type: "banner",
    oral_approved: false,
    banner_url: "https://images.unsplash.com/photo-1485827404703-89b55fcc595e?w=800&q=80",
    thumbnail_url: null,
    slides_url: null,
    article_url: null,
    pitch_youtube_url: null,
    github_url: null,
    status: "rascunho",
    keywords: ["BACnet", "BMS", "HVAC", "automação predial", "LEED"],
    members: [
      { name: "Fernando Leal", email: "fernando@senaisp.edu.br" },
    ],
    created_date: "2026-04-01T09:00:00Z",
    updated_date: "2026-04-28T12:00:00Z",
    created_by: "admin@senaisp.edu.br",
  },
];

export const MOCK_EVALUATIONS = [
  {
    id: "eval-1",
    project_id: "proj-1",
    evaluator_name: "Carlos Alberto Mendes",
    evaluation_type: "professor",
    criteria_scores: [
      { criteria_id: "c1", criteria_name: "[Banco de Dados] Modelagem Relacional", score: 9 },
      { criteria_id: "c2", criteria_name: "[Banco de Dados] Normalização", score: 8 },
      { criteria_id: "c3", criteria_name: "[Redes] Configuração de Protocolos", score: 10 },
    ],
    comments: "Projeto de excelente qualidade técnica, bem documentado e com resultados comprovados.",
    created_date: "2026-04-15T10:00:00Z",
    created_by: "admin@senaisp.edu.br",
  },
  {
    id: "eval-2",
    project_id: "proj-3",
    evaluator_name: "Carlos Alberto Mendes",
    evaluation_type: "aluno",
    criteria_innovation: 9,
    criteria_technical: 8,
    criteria_presentation: 9,
    criteria_relevance: 10,
    comments: "Solução muito relevante para o mercado, apresentação clara e objetiva.",
    created_date: "2026-04-16T14:00:00Z",
    created_by: "admin@senaisp.edu.br",
  },
];

export const MOCK_CRITERIA_LISTS = [
  {
    id: "list-1",
    name: "Banco de Dados",
    description: "Critérios para avaliação de projetos com foco em modelagem e persistência de dados",
    owner_email: "admin@senaisp.edu.br",
    criteria: [
      { name: "Modelagem Relacional", description: "Qualidade do diagrama ER e normalização", weight: 2 },
      { name: "Normalização", description: "Aplicação das formas normais (1FN, 2FN, 3FN)", weight: 1 },
      { name: "Performance de Queries", description: "Uso correto de índices e otimização de consultas", weight: 1 },
    ],
    created_date: "2026-03-01T09:00:00Z",
    created_by: "admin@senaisp.edu.br",
  },
  {
    id: "list-2",
    name: "Redes de Computadores",
    description: "Avaliação de aspectos de conectividade, protocolos e segurança de rede",
    owner_email: "admin@senaisp.edu.br",
    criteria: [
      { name: "Configuração de Protocolos", description: "Correto uso de TCP/IP, HTTP, MQTT, etc.", weight: 2 },
      { name: "Segurança", description: "Aplicação de criptografia e autenticação", weight: 2 },
      { name: "Topologia", description: "Adequação da topologia ao problema", weight: 1 },
    ],
    created_date: "2026-03-02T09:00:00Z",
    created_by: "admin@senaisp.edu.br",
  },
];

export const MOCK_USER_PROFILES = [
  {
    id: "profile-1",
    user_email: "admin@senaisp.edu.br",
    full_name: "Carlos Alberto Mendes",
    user_type: "professor",
    department: "Engenharia Elétrica",
    active: true,
    created_date: "2026-01-10T09:00:00Z",
  },
  {
    id: "profile-2",
    user_email: "prof.fernanda@senaisp.edu.br",
    full_name: "Fernanda Lima",
    user_type: "professor",
    department: "Mecatrônica",
    active: true,
    created_date: "2026-01-11T09:00:00Z",
  },
  {
    id: "profile-3",
    user_email: "lucas@senaisp.edu.br",
    full_name: "Lucas Ferreira",
    user_type: "aluno",
    registration: "2024001",
    course: "Mecatrônica",
    active: true,
    created_date: "2026-01-15T09:00:00Z",
  },
  {
    id: "profile-4",
    user_email: "pedro@senaisp.edu.br",
    full_name: "Pedro Henrique Rocha",
    user_type: "aluno",
    registration: "2024002",
    course: "Mecatrônica",
    active: true,
    created_date: "2026-01-15T09:00:00Z",
  },
  {
    id: "profile-5",
    user_email: "juliana@senaisp.edu.br",
    full_name: "Juliana Martins",
    user_type: "aluno",
    registration: "2024003",
    course: "Análise e Desenvolvimento de Sistemas",
    active: true,
    created_date: "2026-01-16T09:00:00Z",
  },
  {
    id: "profile-6",
    user_email: "thiago@senaisp.edu.br",
    full_name: "Thiago Barbosa",
    user_type: "aluno",
    registration: "2024004",
    course: "Logística",
    active: true,
    created_date: "2026-01-17T09:00:00Z",
  },
  {
    id: "profile-7",
    user_email: "gabriela@senaisp.edu.br",
    full_name: "Gabriela Fonseca",
    user_type: "aluno",
    registration: "2024005",
    course: "Química Industrial",
    active: true,
    created_date: "2026-01-18T09:00:00Z",
  },
  {
    id: "profile-8",
    user_email: "henrique@senaisp.edu.br",
    full_name: "Henrique Azevedo",
    user_type: "aluno",
    registration: "2024006",
    course: "Gestão Industrial",
    active: true,
    created_date: "2026-01-19T09:00:00Z",
  },
];

export const MOCK_GROUPS = [
  {
    id: "group-1",
    name: "Grupo Alpha-4",
    description: "Grupo de desenvolvimento do projeto IoT Energético",
    owner_email: "lucas@senaisp.edu.br",
    members: [
      { email: "ana@senaisp.edu.br", name: "Ana Paula Costa", status: "accepted" },
      { email: "bruno@senaisp.edu.br", name: "Bruno Souza", status: "accepted" },
      { email: "carol@senaisp.edu.br", name: "Carolina Silva", status: "pending" },
    ],
    created_date: "2026-02-01T09:00:00Z",
    created_by: "lucas@senaisp.edu.br",
  },
  {
    id: "group-2",
    name: "RoboTeam SP",
    description: "Equipe de robótica colaborativa",
    owner_email: "pedro@senaisp.edu.br",
    members: [
      { email: "mariana@senaisp.edu.br", name: "Mariana Oliveira", status: "accepted" },
    ],
    created_date: "2026-02-05T10:00:00Z",
    created_by: "pedro@senaisp.edu.br",
  },
];

export const MOCK_PHOTOS = [
  {
    id: "photo-1",
    photo_url: "https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=600&q=80",
    caption: "Abertura oficial da I Mostra de Projetos Integradores UniSENAI SP",
    category: "abertura",
    created_date: "2026-04-28T09:00:00Z",
    created_by: "admin@senaisp.edu.br",
  },
  {
    id: "photo-2",
    photo_url: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&q=80",
    caption: "Equipes apresentando seus projetos no salão principal",
    category: "apresentacoes",
    created_date: "2026-04-28T10:00:00Z",
    created_by: "admin@senaisp.edu.br",
  },
  {
    id: "photo-3",
    photo_url: "https://images.unsplash.com/photo-1475721027785-f74eccf877e2?w=600&q=80",
    caption: "Demonstração do braço robótico colaborativo",
    category: "apresentacoes",
    created_date: "2026-04-28T11:00:00Z",
    created_by: "admin@senaisp.edu.br",
  },
  {
    id: "photo-4",
    photo_url: "https://images.unsplash.com/photo-1523580494863-6f3031224c94?w=600&q=80",
    caption: "Premiação dos projetos destaques da mostra",
    category: "premiacao",
    created_date: "2026-04-28T17:00:00Z",
    created_by: "admin@senaisp.edu.br",
  },
  {
    id: "photo-5",
    photo_url: "https://images.unsplash.com/photo-1517048676732-d65bc937f952?w=600&q=80",
    caption: "Networking entre alunos e professores",
    category: "geral",
    created_date: "2026-04-28T15:00:00Z",
    created_by: "admin@senaisp.edu.br",
  },
  {
    id: "photo-6",
    photo_url: "https://images.unsplash.com/photo-1529156069898-49953e39b3ac?w=600&q=80",
    caption: "Encerramento e foto oficial com todos os participantes",
    category: "encerramento",
    created_date: "2026-04-28T18:00:00Z",
    created_by: "admin@senaisp.edu.br",
  },
];